<?php
//  This file is part of Kreda.
//
//  Kreda is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Affero Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Kreda is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Affero Public License for more details.
//
//  You should have received a copy of the GNU Affero Public License
//  along with Kreda.  If not, see <http://www.gnu.org/licenses/>.
//
//  Diese Datei ist Teil von Kreda.
//
//  Kreda ist Freie Software: Sie können es unter den Bedingungen
//  der GNU Affero Public License, wie von der Free Software Foundation,
//  Version 3 der Lizenz oder (nach Ihrer Wahl) jeder späteren
//  veröffentlichten Version, weiterverbreiten und/oder modifizieren.
//
//  Kreda wird in der Hoffnung, dass es nützlich sein wird, aber
//  OHNE JEDE GEWÄHELEISTUNG, bereitgestellt; sogar ohne die implizite
//  Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
//  Siehe die GNU Affero Public License für weitere Details.
//
//  Sie sollten eine Kopie der GNU Affero Public License zusammen mit diesem
//  Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.

    // Methoden: Name, Anlass, Bedeutung, Tipps/Probleme
    $methods=array(
        1=> array('name'=>'Unterrichtseinstiegs-Gespräch',
            'occasion'=>'zu Beginn einer Reihe; auch nach ersten Experimenten',
            'intend'=>'Bedeutung des Themas; weder falsch noch richtig; Neugierde, an Bekanntes anknüpfen; viele Schüler, schafft Themenklarheit; fördert fachliches Interesse, Lernbereitschaft',
            'pointer'=>'Guter Einstieg - Zeit geben; offen beantworten lassen; Antworten zum später aufgreifen; hohe Aktivität: Gesprächsdauer; niedrige Aktivität: S kurz notieren lassen, was ihnen einfällt'),
        2=> array('name'=>'Brainstorming',
            'occasion'=>'Einstieg; (bei Fragen)',
            'intend'=>'freies Gedankenäußern; an Bekanntes anknüpfen; Ideen & Fragen formulieren',
            'pointer'=>'zeitlich begrenzen; Quatschbeiträge ignorieren; Nennungen im Unterricht verfolgen -> danach klären, wann...; Aufwand'),
        3=> array('name'=>'doppelter Sitzkreis (Kugellager)',
            'occasion'=>'nach einem Film (Inhaltsreproduktion)',
            'intend'=>'intensive Reproduktion von Gehörtem; gute Speicherung',
            'pointer'=>'aufwändig'),
        4=> array('name'=>'Schreibgespräch',
            'occasion'=>'Vorwissen sammeln; was will ich langfristig behalten',
            'intend'=>'absolute Stille (Musik?); gut durchdachte Einfälle, intensiv; auch als "schriftliches Brainstorming"',
            'pointer'=>'fördert und setzt Disziplin voraus; anfangs befremdlich, erstes Schreiben dauert; auch Unsinn vorlesen; im zweiten Schritt filtern, was von Bedeutung sein könnte'),
        5=> array('name'=>'Redekette',
            'occasion'=>'Einstieg; Sitzkreis vorteilhaft',
            'intend'=>'offene Frage/Impuls vom Lehrer; Schüler rufen sich gegenseitig auf (Lehrer bricht nicht ab, macht Notizen); am Ende zusammenfassen; im Unterricht auf Äußerungen eingehen',
            'pointer'=>'Jungen nehmen oft nur Jungen dran (Regeln erarbeiten); Einstiegsfrage muss klar sein und viele Beantwortungsmöglichkeiten bieten (Rückfragen überflüssig); Schüler, die sich noch keine Möglichkeit hatten, bevorzugt drannehmen; auch Schüler dran nehmen, die sich nicht melden'),
        6=> array('name'=>'Sitzkreis',
            'occasion'=>'',
            'intend'=>'wohltuende Gesprächsatmosphäre; Distanzabnahme, Körpersprache',
            'pointer'=>'Regern beim Aufbau: nicht sprechen, Stühle/Tische heben, Zeitdauer - alle versuchen diese einzuhalten; Zielplan an Tafel'),
        7=> array('name'=>'Lehrervortrag',
            'occasion'=>'Anfangsphase',
            'intend'=>'Visualisierungen, strukturiert; Zwischenfragen sind möglich; Schüler können in Ruhe zuhören, ohne die Gefahr aufgerufen zu werden',
            'pointer'=>'selten und wohl dosiert anwenden; Zeit stoppen und ansagen -> Ruhe; Höraufträge vergeben -> Zusammenfassung; bis zu "Klassenstufe + 2min" lang; Lautstärke und Sprechgeschwindigkeit variieren; mit Frage oder Rätsel beenden'),
        8=> array('name'=>'Frontalunterricht',
            'occasion'=>'Anfangsphase, Exemplarisches',
            'intend'=>'fragend-entwickelndes Verfahren',
            'pointer'=>'unbeliebt bei Schülern; Häufigkeit im Blick behalten; was denken die Schüler wirklich?; Schüler aktivieren; Gesprächsmoderation wichtig; max. 50%'),
        9=> array('name'=>'Einzelarbeit',
            'occasion'=>'Anwendung; WH; Erarbeitung (mehr als Gruppe wenn rein kognitiv, erst bei rel. Sicherheit)',
            'intend'=>'Stillarbeit; Auftrag und Schritte klar, Sicherheitsgewinn; ohne Ablenkung, allein, nicht schnell aufgeben; gut für Diffenrenzierung; auch als Einstieg bei Disziplinproblemen',
            'pointer'=>'junge Schüler: mehrere kurze Abschnitte; unbeliebt (Prüfungssituations-Ähnlichkeit); Zeit (Uhr aufstellen) fest; Rückfragen in Anfangsphase, dann Stille; wenn es bei schwächeren Schülern gut läuft, von ihnen vortragen lassen; Lösungen (gegen Ende) geben; nicht überfallartig (vorher ankündigen)'),
        10=> array('name'=>'Partnerarbeit',
            'occasion'=>'Erarbeitung',
            'intend'=>'geeignet, wenn Aufgabe komplex ist, aber für Gruppen zu wenig Aufteilung möglich ist; gegenseitige Hilfe; Arbeitsteilung',
            'pointer'=>'Blickkontakt zugewandt; klar: was wird erwartet; viele sollen Ergebnisse vorstellen; Fehlerkorrektur erst nach der Präsentation'),
        11=> array('name'=>'Gruppenarbeit',
            'occasion'=>'Anwendung; vorher exemplarische Erarbeitung',
            'intend'=>'Leistungsstarke -> Teamteacher; gut für Differenzierung (unterschiedliche Schwierigkeitsgrade); Bewertung der Gruppenarbeit möglich (S. 36); auch besonders Gute/Schlechte -> Einzelnote',
            'pointer'=>'beliebt; häufig bei Älteren einsetzen (auch in Erarbeitungsphase); es gibt Diktatoren; 45min-Unterricht oft zu kurz mit Erarbeitung/Präsentation; Gruppentische leise einrichten; Arbeitsplanung S. 34; Gruppeneinteilung S. 35'),
        12=> array('name'=>'Gruppenpuzzle',
            'occasion'=>'komplexe Aufgaben',
            'intend'=>'1. Phase {1,2,3,4,5} {1,2,3,4,5}... 2. Phase {1,1,1,1,1} {2,2,2,2,2}...; komplexe Aufgabe -> Lösung besprechen - dann erneute Beratung; gute Zuhörfähigkeit; kurzweilig',
            'pointer'=>'bei Regelwidrigkeiten führt es zu Chaos; Ablauf und Arrangement klären; Statements aller Gruppen (Sprecher); feste Zeiten vereinbaren'),
        13=> array('name'=>'Lesekompetenzförderung',
            'occasion'=>'',
            'intend'=>'fachsprachliche Texte; nicht den Schülern die Arbeit abnehmen',
            'pointer'=>'Vorgehen:; Lesen lassen -> in 1 Satz Inhalt notieren lassen; Text Satz für Satz vorlesen lassen - Pause; Daumen "verstanden" / "nicht verstanden"; zusammenfassen lassen; unverständliche Sätze nochmals vorlesen'),
        14=> array('name'=>'Fantasiereise',
            'occasion'=>'Übung; WH; KA',
            'intend'=>'Stressabbau; konzentrationsförderung',
            'pointer'=>''),
        15=> array('name'=>'Experiment',
            'occasion'=>'Simulation z.B. am PC',
            'intend'=>'Aufwand Kosten-Nutzen; Auge, Ohr... wird genutzt',
            'pointer'=>'Vermutungen äußern lassen (auch Vorwissen; Vorgaben erfüllen, die Schüler nicht schaffen können; Anforderungen klären'),
        16=> array('name'=>'Rollenspiel',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        17=> array('name'=>'Schülerpräsentation',
            'occasion'=>'Höhepunkt nach Gruppenarbeiten; HA',
            'intend'=>'wichtige Qualifikation fürs Berufsleben; Lernerfolg der Gesamtgruppe geringer; Größere Auswertung S. 50f',
            'pointer'=>'genaue Vorgaben; alle Schüler im Team sind dran; deutliche Zäsur zw. Arbeit und Vortrag; maximale Dauer; vor allem die Klasse beobachten'),
        18=> array('name'=>'Diskussion',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        19=> array('name'=>'Fishbowl-Diskussion',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        20=> array('name'=>'Pro- & Kontra-Debatte',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        21=> array('name'=>'Stationenlernen',
            'occasion'=>'ganze Einheiten abdeckbar',
            'intend'=>'Pflicht- und Wahlstationen; gute Differenzierbarkeit',
            'pointer'=>'klare Organisations-Regeln; Lehrerplanungsaufwand hoch - Minimierung wenn Schulbücher genutzt werden; Achtung: Entscheidungsfreiheit kann missbraucht werden'),
        22=> array('name'=>'Planspiel',
            'occasion'=>'description',
            'intend'=>'',
            'pointer'=>''),
        23=> array('name'=>'Metaplanmethode',
            'occasion'=>'ab Kl. 8',
            'intend'=>'Integration in Planung und Gestaltung des Unterrichts; was müchte ich erfahren',
            'pointer'=>'für Rechenarten... (Mathe) nicht so geeignet'),
        24=> array('name'=>'Filmeinsatz',
            'occasion'=>'',
            'intend'=>'beliebtes, bekanntes Medium',
            'pointer'=>'Filmprotokoll mit Stationen (Verlauf) anlegen - später nutzen'),
        25=> array('name'=>'Projektunterricht',
            'occasion'=>'',
            'intend'=>'am Ende ein vorzeigbares Produkt; prägt sich tiefer ein, macht praktisch Spaß; hohe Motivation auch für Wissensvermittlung',
            'pointer'=>''),
        26=> array('name'=>'Schüler unterrichten Schüler',
            'occasion'=>'ab Kl. 8',
            'intend'=>'Lernen durch lehren effektiv; Thema und Rolle wählbar -> innere Differenzierung',
            'pointer'=>'zeitaufwändig, aber erfahrungswirksam; S. 77 (abwandeln)'),
        27=> array('name'=>'Aufgabenkartei',
            'occasion'=>'nach Behandlung eines Themas',
            'intend'=>'Schüler erstellen Aufgaben (Aufgabenformat wird an Bsp. eingeführt oder Orientierung an Buchaufgaben) für ihre Mitschüler. Werden in einem Kasten gesammelt und in einer Übungsphase bearbeitet.',
            'pointer'=>''),
        28=> array('name'=>'Freiarbeit/Wochenplanarbeit',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        29=> array('name'=>'Gutachten',
            'occasion'=>'',
            'intend'=>'Inszenierung einer (fiktiven) Auftragsvergabe. Schülergruppen bearbeiten das Problem und präsentieren/begründen/beantworten Rückfragen zum erstellten Gutachten.',
            'pointer'=>''),
        30=> array('name'=>'Ich-Du-Wir (Think-Pair-Share)',
            'occasion'=>'',
            'intend'=>'Hinreichend offenes Problem stellen; Jeder arbeitet für sich an Lösungsideen; Ideen werden mit dem Partner ausgetauscht (Ansätze vergleichen, Irrwege besprechen, offene Fragen festhalten); Ergebnisse in Gruppe/Klasse präsentieren (verschiedene Wege vergleichen)',
            'pointer'=>''),
        31=> array('name'=>'Knobelteam',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        32=> array('name'=>'Lerntagebuch',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        33=> array('name'=>'Sammelalbum',
            'occasion'=>'Ende eines Themas',
            'intend'=>'Begriffe werden aufgeschrieben (z.B. 6 von 9 Felder); Tausch-Partner dürfen Begriffe ergänzen, wenn sie diese korrekt erklären können; In größerer Runde werden die Begriffe in einer Begriffslandkarte angeordnet - Aushang und besprechen',
            'pointer'=>''),
        34=> array('name'=>'Quiz',
            'occasion'=>'',
            'intend'=>'Wer ist Quizmaster, Jury, Ratende(r)?; Schüler erstellen Fragen und Antworten; Spielen; nicht gelöste Fragen klären bzw. Fragenverbesserung',
            'pointer'=>''),
        35=> array('name'=>'Passt! - Passt nicht!',
            'occasion'=>'',
            'intend'=>'Lehrer/Schüler hält eine geheime(!) Regel schriftlich fest; Schüler raten, ob ein Objekt die Regel erfüllt oder nicht; Wer glaubt, die Regel gefunden zu haben kann sie an weiteren Objekten prüfen; die letzten berichten von ihren Vermutungen - die anderen formulieren die Regel in eig. Worten und erklären die entscheidenden Ideen.',
            'pointer'=>''),
        36=> array('name'=>'Platzdeckchen',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        37=> array('name'=>'Poster',
            'occasion'=>'',
            'intend'=>'Erstellen; Museumsrundgang',
            'pointer'=>''),
        38=> array('name'=>'Redaktion',
            'occasion'=>'',
            'intend'=>'Schriftstück verfassen (als HA oder Stillarbeit); in GA nacheinander vorlesen - spontane Rückmeldung und dann Schritt für Schritt - Verständnis, Inhalt und Darstellungsart; Textverbesserungen (eine Fassung als Beste oder eine gemeinsame neue)',
            'pointer'=>''),
        39=> array('name'=>'Sammeln-Ordnen-Strukturieren',
            'occasion'=>'',
            'intend'=>'Schüler sammeln Gedanken zum vorgegebenen Thema auf Karten (Bsp., Begriffe, Fragen...); ordnen Karten an Tafel und stellen Verbindungen zwischen ihnen her; Ergebnisse präsentieren und ausstellen',
            'pointer'=>''),
        40=> array('name'=>'Schreibgespräch',
            'occasion'=>'Offene Aufgaben',
            'intend'=>'Aufgabenstellung; erste Ideen notieren; Blätterweitergabe (ohne Rückfragen) und arbeiten an der Stelle weiter; diskutieren',
            'pointer'=>''),
        41=> array('name'=>'Steckbrief',
            'occasion'=>'',
            'intend'=>'mehrere Objekte auswählen; Schüler erhalten ein/mehrere Objekte und formulieren Steckbriefbeschreibungen; Schüler lesen Steckbriefe vor und ordnen zu; optimale Steckbriefe können ausgehängt werden',
            'pointer'=>''),
        42=> array('name'=>'Stille Post',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        43=> array('name'=>'Streitgespräch',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        44=> array('name'=>'Tandem',
            'occasion'=>'',
            'intend'=>'',
            'pointer'=>''),
        45=> array('name'=>'Was bin ich?',
            'occasion'=>'',
            'intend'=>'Lehrer/Schüler denkt sich ein Objekt aus und vertritt es in der Raterunde; Rest stellt Fragen; später: welche Runden waren leicht, welche schwer, warum?',
            'pointer'=>'')
    );
?>
